static std::vector<std::string> pairingMessages {
  "Searching for victim",
  "Search boat's cook",
  "Triggering final boss",
  "Hero captain looking for work",
  "Is anyone there? hello",
  "Searching for ez target",
  "Activate Radar"
};

static std::vector<std::string> waitingMessages {
  "Waiting for slow admiral to position fleet",
  "Waiting for looser to get startet",
  "Waiting for other player to finish fleet setup",
  "Heating up barrels",
  "Preparing for battle"
};
